import { StyleSheet } from "react-native";
import { borderRadius, colors, fontSize, fontWeight, spacing } from "../../design";
import { TAB_BAR_CLEARANCE } from "./constants";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    paddingTop: spacing.sm,
    paddingHorizontal: spacing["2xl"],
    paddingBottom: spacing["4xl"] + TAB_BAR_CLEARANCE,
    gap: spacing["2xl"],
  },
  screenMeta: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.textSecondary,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingTop: spacing.xl,
    gap: spacing.lg,
  },
  headerCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  headerEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: colors.textTertiary,
  },
  headerTitle: {
    fontSize: 42,
    fontWeight: "800",
    lineHeight: 44,
    color: colors.text,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 24,
    letterSpacing: 0,
    textTransform: "none",
    color: colors.text,
  },
  sectionIconButton: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.lg,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    backgroundColor: "rgba(20, 20, 22, 0.92)",
  },
  sectionIconButtonPressed: {
    backgroundColor: "rgba(16, 16, 18, 0.96)",
    transform: [{ scale: 0.96 }],
  },
  todayPreviewCard: {
    position: "relative",
    overflow: "hidden",
    minHeight: 148,
    justifyContent: "center",
    borderRadius: 22,
    borderCurve: "continuous",
    paddingRight: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    borderWidth: 1,
    borderColor: "rgba(6, 16, 24, 0.05)",
    backgroundColor: "#CAE95A",
    boxShadow: "0px 12px 24px rgba(6, 16, 24, 0.1)",
  },
  todayPreviewCardPressed: {
    transform: [{ scale: 0.988 }],
  },
  todayPreviewContent: {
    paddingLeft: spacing.lg,
    paddingRight: 72,
    position: "relative",
    zIndex: 2,
  },
  todayPreviewCopy: {
    paddingLeft: spacing.lg,
    gap: spacing.sm,
  },
  todayPreviewSectionSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: colors.textSecondary,
  },
  todayPreviewMetaInline: {
    paddingLeft: spacing.lg,
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(6, 16, 24, 0.52)",
  },
  todayPreviewTitleRow: {
    marginBottom: spacing.sm,
  },
  todayPreviewTitleIconFrame: {
    flexShrink: 0,
  },
  todayPreviewTitleIcon: {
    width: 52,
    height: 52,
    transform: [{ translateX: -8 }],
    opacity: 0.88,
  },
  todayPreviewTitle: {
    flex: 1,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    color: colors.primaryForeground,
  },
  todayPreviewSummaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.xs,
  },
  todayPreviewSummaryGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  todayPreviewSummaryItem: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 2,
  },
  todayPreviewSummaryWeight: {
    fontSize: 18,
    lineHeight: 20,
    fontWeight: fontWeight.medium,
    color: colors.primaryForeground,
  },
  todayPreviewSummaryReps: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: fontWeight.medium,
    color: "rgba(6, 16, 24, 0.64)",
  },
  todayPreviewSummarySeparator: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
    color: "rgba(6, 16, 24, 0.3)",
  },
  todayPreviewPlayButton: {
    position: "absolute",
    right: spacing.lg,
    top: spacing["2xl"],
    width: 46,
    height: 46,
    borderRadius: 23,
    borderCurve: "continuous",
    backgroundColor: "rgba(6, 16, 24, 0.88)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
    boxShadow: "0px 6px 14px rgba(6, 16, 24, 0.1)",
  },
  todayEmptyState: {
    gap: spacing.sm,
  },
  todayEmptyTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  reorderHint: {
    marginTop: -spacing.xs,
  },
  reorderIntroCard: {
    gap: spacing.sm,
  },
  reorderIntroText: {
    color: colors.textSecondary,
  },
  weekGrid: {
    gap: spacing.md,
  },
  weekGridRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  weekGridCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 148,
    gap: spacing.lg,
  },
  weekGridSpacer: {
    flex: 1,
  },
  weekCarouselCard: {
    justifyContent: "space-between",
    gap: spacing["2xl"],
    borderRadius: 28,
    borderCurve: "continuous",
    borderWidth: 1,
    padding: spacing.lg,
    boxShadow: "0px 22px 44px rgba(0, 0, 0, 0.18)",
  },
  weekCarouselCardPressed: {
    opacity: 0.95,
    transform: [{ scale: 0.985 }],
  },
  weekCarouselCardToday: {
    borderColor: "rgba(214, 255, 96, 0.28)",
  },
  weekCarouselCardCompleted: {
    opacity: 0.76,
  },
  weekCarouselCardSquat: {
    backgroundColor: colors.surfaceElevated,
    borderColor: "rgba(146, 180, 245, 0.12)",
  },
  weekCarouselCardBench: {
    backgroundColor: colors.surfaceElevated,
    borderColor: "rgba(228, 134, 116, 0.12)",
  },
  weekCarouselCardDeadlift: {
    backgroundColor: colors.surfaceElevated,
    borderColor: "rgba(117, 180, 194, 0.12)",
  },
  weekCarouselCardPress: {
    backgroundColor: colors.surfaceElevated,
    borderColor: "rgba(157, 207, 100, 0.12)",
  },
  weekCarouselTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  weekCarouselThumbnailFrame: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  weekGridThumbnailFrame: {
    width: spacing["4xl"],
    height: spacing["4xl"],
  },
  weekCarouselBody: {
    gap: spacing.sm,
  },
  weekCarouselMetaLight: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(245, 245, 247, 0.62)",
  },
  weekCarouselMetaDark: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(245, 245, 247, 0.62)",
  },
  weekCarouselTitleLight: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: "#FAFAFB",
  },
  weekCarouselTitleDark: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: "#FAFAFB",
  },
  weekCarouselSummaryLight: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "500",
    color: "rgba(245, 245, 247, 0.78)",
  },
  weekCarouselSummaryDark: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "500",
    color: "rgba(245, 245, 247, 0.78)",
  },
  weekList: {
    position: "relative",
    gap: spacing.md,
  },
  weekRow: {
    zIndex: 0,
  },
  weekRowDragSource: {
    position: "absolute",
    left: 0,
    right: 0,
    opacity: 0,
  },
  floatingDraggedCard: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 20,
    opacity: 0.96,
    boxShadow: "0px 24px 60px rgba(0, 0, 0, 0.32)",
  },
  dropPlaceholder: {
    borderRadius: borderRadius.xl,
    borderCurve: "continuous",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(255, 255, 255, 0.12)",
    backgroundColor: colors.surfaceMuted,
    opacity: 0.55,
  },
  cardContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.md,
  },
  cardLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  cardText: {
    flex: 1,
    gap: 2,
  },
  cardMetaText: {
    flexShrink: 1,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  cardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    flexShrink: 0,
  },
  thumbnailFrame: {
    width: 68,
    height: 68,
    borderRadius: 18,
    borderCurve: "continuous",
    overflow: "hidden",
    padding: spacing.xs,
    flexShrink: 0,
  },
  thumbnailImage: {
    width: "100%",
    height: "100%",
  },
  dragHandle: {
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: borderRadius.lg,
    borderCurve: "continuous",
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    minWidth: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  dragHandleRight: {
    marginLeft: spacing.xs,
  },
  dragHandleActive: {
    borderColor: "rgba(255, 255, 255, 0.14)",
    backgroundColor: colors.surfaceGlassStrong,
  },
  dragHandleText: {
    fontSize: 16,
    color: colors.textSecondary,
    fontWeight: "700",
    lineHeight: 16,
  },
  liftName: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.text,
  },
  activitySummaryCard: {
    padding: spacing.md,
  },
  activitySummarySurface: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  activitySummaryItemContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  activitySummaryItem: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.lg,
    gap: spacing.xs,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  activitySummaryItemDivider: {
    borderRightWidth: 1,
    borderRightColor: "rgba(255, 255, 255, 0.08)",
    height: 62,
  },
  activitySummaryMetaRow: {
    display: 'flex',
    flexDirection: "row",
    alignItems: "center",
    justifyContent: 'center',
    gap: spacing.xs,
  },
  activitySummaryLabel: {
    flexShrink: 1,
    fontSize: fontSize.sm,
    lineHeight: 18,
    fontWeight: "700",
    color: colors.text,
  },
  activitySummaryValueRow: {
    minHeight: 36,
    justifyContent: "flex-end",
  },
  activitySummaryValue: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: fontWeight.bold,
    color: colors.text,
  },
  upcomingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.md,
  },
  upcomingTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.text,
    flex: 1,
  },
  chevron: {
    fontSize: 24,
    color: colors.textTertiary,
  },
});
